# PyCoMo CycleBreaker #
This tutorial show-cases the use of CycleBreaker. Here, efmtool is used to enumerate all WONCY cycles (witout net conversion cycles), and then binary variables are used to forbid all reactions of a cycle being active at the same time - in turn breaking the cycle.

The expected runtime for this notebook is less than 10 minutes.

In [1]:
import cobra

In [2]:
import pycomo
pycomo.configure_logger(level="info")

2026-03-15 13:17:05,718 - PyCoMo - INFO - Logger initialized.

In [3]:
conf = cobra.Configuration()
conf.solver = "gurobi"
conf.processes = 8

## Model import ##
We are using two genome-scale models of the AGORA2 collection:
 - Bacteroides stercoris ERR2230062
 - Blautia torques ERR1022325

In [4]:
test_model_dir = "../data/use_case/cyclebreaker"
named_models = pycomo.load_named_models_from_dir(test_model_dir, file_format="mat")

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19

No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e, p
No defined compartments in model model. Compartments will be deduced heuristically using regular expressions.
Using regular expression found the following compartments:c, e

In [5]:
named_models

{'Bacteroides_stercoris_ERR2230062': <Model model at 0x7f7f6bbef940>,
 'Blautia_torques_ERR1022325': <Model model at 0x7f7f6bf84490>}

In [6]:
single_org_models = []
for name, model in named_models.items():
    print(name)
    single_org_model = pycomo.SingleOrganismModel(model, name)
    single_org_models.append(single_org_model)

Bacteroides_stercoris_ERR2230062
Read LP format model from file /tmp/tmpnkc7tfyz.lp
Reading time = 0.01 seconds
: 1174 rows, 2510 columns, 10030 nonzeros
Blautia_torques_ERR1022325
Read LP format model from file /tmp/tmpniplef8i.lp
Reading time = 0.01 seconds
: 1034 rows, 2358 columns, 10044 nonzeros

In [7]:
community_name = "cyclebreaker_test"
com_model_obj = pycomo.CommunityModel(single_org_models, community_name)

In [8]:
com_model_obj.summary()

2026-03-15 13:17:12,949 - PyCoMo - INFO - No community model generated yet. Generating now:

Read LP format model from file /tmp/tmp7cupkw69.lp
Reading time = 0.01 seconds
: 1174 rows, 2510 columns, 10030 nonzeros

2026-03-15 13:17:14,974 - PyCoMo - INFO - Identified biomass reaction from objective: bio1
2026-03-15 13:17:14,975 - PyCoMo - INFO - Note: no products in the objective function, adding biomass to it.

Read LP format model from file /tmp/tmpc8sj2rw2.lp
Reading time = 0.01 seconds
: 1034 rows, 2358 columns, 10044 nonzeros

2026-03-15 13:17:33,174 - PyCoMo - INFO - Identified biomass reaction from objective: bio1
2026-03-15 13:17:33,175 - PyCoMo - INFO - Note: no products in the objective function, adding biomass to it.

Read LP format model from file /tmp/tmpk2ff9wa6.lp
Reading time = 0.03 seconds
: 2829 rows, 5946 columns, 20512 nonzeros
Read LP format model from file /tmp/tmpi_dn7kab.lp
Reading time = 0.06 seconds
: 5927 rows, 12308 columns, 42154 nonzeros

2026-03-15 13:18:02,206 - PyCoMo - WARNING - Not all reactions in the model are mass and charge balanced. To check which reactions are imbalanced, please run the get_unbalanced_reactions method of this CommunityModel object
2026-03-15 13:18:02,209 - PyCoMo - INFO - Generated community model.

## Cycle enumeration ##

In [9]:
cycles = pycomo.helper.cyclebreaker.enumerate_cycles_in_com_model(com_model_obj)

## CycleBreaker ##

### Test flux without medium ###
Check how many external reactions can carry flux without a medium present. These reactionse are part of a cycle.

In [10]:
com_model_obj.medium = {}

In [11]:
fva_no_medium = com_model_obj.run_fva(fva_mu_c=0)  # FVA on all external reactions

2026-03-15 13:19:10,223 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmp2_pqlewp.lp
Reading time = 0.07 seconds
: 5928 rows, 12309 columns, 42153 nonzeros

2026-03-15 13:19:12,965 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpqq5gm5qv.lp
Reading time = 0.06 seconds
: 5928 rows, 12309 columns, 42153 nonzeros

2026-03-15 13:19:15,581 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmp5tfupd2_.lp
Reading time = 0.06 seconds
: 5928 rows, 12309 columns, 42153 nonzeros

2026-03-15 13:19:17,972 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmp314cm4xd.lp
Reading time = 0.07 seconds
: 5928 rows, 12309 columns, 42153 nonzeros

2026-03-15 13:19:20,344 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpg7zu_o41.lp
Reading time = 0.06 seconds
: 5928 rows, 12309 columns, 42153 nonzeros

2026-03-15 13:19:22,856 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpsoqypgjs.lp
Reading time = 0.06 seconds
: 5928 rows, 12309 columns, 42153 nonzeros

2026-03-15 13:19:25,288 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmp9zmk5jp5.lp
Reading time = 0.06 seconds
: 5928 rows, 12309 columns, 42153 nonzeros

2026-03-15 13:19:28,695 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpqevwfsb7.lp
Reading time = 0.06 seconds
: 5928 rows, 12309 columns, 42153 nonzeros

2026-03-15 13:19:34,977 - PyCoMo - INFO - Processed 20.75% of fva steps
2026-03-15 13:19:38,755 - PyCoMo - INFO - Processed 41.49% of fva steps
2026-03-15 13:19:42,560 - PyCoMo - INFO - Processed 62.24% of fva steps
2026-03-15 13:19:45,939 - PyCoMo - INFO - Processed 82.99% of fva steps
2026-03-15 13:19:48,550 - PyCoMo - INFO - Processed 100.0% of fva steps

Check how many reactions can carry flux (i.e. are not 0)

In [16]:
fva_no_medium[(
    ~fva_no_medium["min_flux"].apply(pycomo.helper.utils.close_to_zero, t=10**-5)
) | (
    ~fva_no_medium["max_flux"].apply(pycomo.helper.utils.close_to_zero, t=10**-5)
)]

,reaction_id,min_flux,max_flux
Bacteroides_stercoris_ERR2230062_TF_gln_L_Bacteroides_stercoris_ERR2230062_e,Bacteroides_stercoris_ERR2230062_TF_gln_L_Bact...,-500.0,500.0
Bacteroides_stercoris_ERR2230062_TF_glu_L_Bacteroides_stercoris_ERR2230062_e,Bacteroides_stercoris_ERR2230062_TF_glu_L_Bact...,-500.0,500.0
Bacteroides_stercoris_ERR2230062_TF_h2o_Bacteroides_stercoris_ERR2230062_e,Bacteroides_stercoris_ERR2230062_TF_h2o_Bacter...,-500.0,500.0
Bacteroides_stercoris_ERR2230062_TF_nh4_Bacteroides_stercoris_ERR2230062_e,Bacteroides_stercoris_ERR2230062_TF_nh4_Bacter...,-500.0,500.0
Blautia_torques_ERR1022325_TF_gln_L_Blautia_torques_ERR1022325_e,Blautia_torques_ERR1022325_TF_gln_L_Blautia_to...,-500.0,500.0
Blautia_torques_ERR1022325_TF_glu_L_Blautia_torques_ERR1022325_e,Blautia_torques_ERR1022325_TF_glu_L_Blautia_to...,-500.0,500.0
Blautia_torques_ERR1022325_TF_h2o_Blautia_torques_ERR1022325_e,Blautia_torques_ERR1022325_TF_h2o_Blautia_torq...,-500.0,500.0
Blautia_torques_ERR1022325_TF_nh4_Blautia_torques_ERR1022325_e,Blautia_torques_ERR1022325_TF_nh4_Blautia_torq...,-500.0,500.0

### Add CycleBreaker constraints ###

In [13]:
pycomo.helper.cyclebreaker.add_cycle_breaker_constraints_for_all_cycles(com_model_obj, cycles)

In [14]:
fva_cyclebreaker = com_model_obj.run_fva(fva_mu_c=0)  # FVA on all external reactions

2026-03-15 13:19:53,684 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmp1vhnxbv0.lp
Reading time = 0.07 seconds
: 6195 rows, 12464 columns, 43877 nonzeros

2026-03-15 13:19:56,068 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpqxbyf0j8.lp
Reading time = 0.06 seconds
: 6195 rows, 12464 columns, 43877 nonzeros

2026-03-15 13:19:58,692 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpv14utidn.lp
Reading time = 0.07 seconds
: 6195 rows, 12464 columns, 43877 nonzeros

2026-03-15 13:20:01,205 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmphxn28vho.lp
Reading time = 0.06 seconds
: 6195 rows, 12464 columns, 43877 nonzeros

2026-03-15 13:20:04,161 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpgg2b0ogr.lp
Reading time = 0.06 seconds
: 6195 rows, 12464 columns, 43877 nonzeros

2026-03-15 13:20:07,128 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpaih856h2.lp
Reading time = 0.06 seconds
: 6195 rows, 12464 columns, 43877 nonzeros

2026-03-15 13:20:10,690 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpszqrf_yb.lp
Reading time = 0.06 seconds
: 6195 rows, 12464 columns, 43877 nonzeros

2026-03-15 13:20:13,285 - PyCoMo - INFO - Logger initialized.

Set parameter Username
Set parameter LicenseID to value 2696585
Academic license - for non-commercial use only - expires 2026-08-19
Read LP format model from file /tmp/tmpg9pm2lz2.lp
Reading time = 0.07 seconds
: 6195 rows, 12464 columns, 43877 nonzeros

2026-03-15 13:22:52,392 - PyCoMo - INFO - Processed 20.75% of fva steps
2026-03-15 13:22:52,412 - PyCoMo - INFO - Processed 41.49% of fva steps
2026-03-15 13:22:52,427 - PyCoMo - INFO - Processed 62.24% of fva steps
2026-03-15 13:23:00,207 - PyCoMo - INFO - Processed 82.99% of fva steps
2026-03-15 13:23:00,220 - PyCoMo - INFO - Processed 100.0% of fva steps

In [17]:
fva_cyclebreaker[(
    ~fva_cyclebreaker["min_flux"].apply(pycomo.helper.utils.close_to_zero, t=10**-5)
) | (
    ~fva_cyclebreaker["max_flux"].apply(pycomo.helper.utils.close_to_zero, t=10**-5)
)]

Empty DataFrame
Columns: [reaction_id, min_flux, max_flux]
Index: []

Now all cycles are broken and none of the cycle reactions can carry flux!